site_name: Musical Notes
repo_url: https://github.com/guidurbano/musical-notes
repo_name: guidurbano/musical-notes
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

watch:
  - musical_notes

plugins:
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [musical_notes]

extra:
  commands:
    run: musical-notes
